// <auto-generated />
using System;
using BS.ReceiptAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BS.ReceiptAnalyzer.Data.Migrations
{
    [DbContext(typeof(ReceiptAnalyzerDbContext))]
    [Migration("20240304203601_InitialAnalysisTask")]
    partial class InitialAnalysisTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BS.ReceiptAnalyzer.Domain.Model.AnalysisTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Progression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImageHash");

                    b.ToTable("AnalysisTask", (string)null);
                });

            modelBuilder.Entity("BS.ReceiptAnalyzer.Domain.Model.AnalysisTaskStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnalysisTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NotificationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTaskId");

                    b.ToTable("AnalysisTaskStep", (string)null);
                });

            modelBuilder.Entity("BS.ReceiptAnalyzer.Domain.Model.AnalysisTaskStep", b =>
                {
                    b.HasOne("BS.ReceiptAnalyzer.Domain.Model.AnalysisTask", null)
                        .WithMany("ProgressionDetails")
                        .HasForeignKey("AnalysisTaskId");
                });

            modelBuilder.Entity("BS.ReceiptAnalyzer.Domain.Model.AnalysisTask", b =>
                {
                    b.Navigation("ProgressionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
